title: ScaLab @ KTH
description: Scalable Parallel System Research Group
google_analytics: G-4TQP6KS97Z
external_page:
      group_url: https://www.kth.se/social/group/scalable-computing/
theme: jekyll-theme-slate
